# Site settings
title: Jake Tarnow
subtitle: Not Your Average Engineer
email: jacobtarnow@gmail.com
description: My personal blog dumping knowledge bombs on all things computer science and security/hacking
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jaketarnow.github.io" # the base hostname & protocol for your site
author:
street_address: 
city: San Francisco
state: CA
zip_code:
country:
phone:

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# Social settings
500px_url:
facebook_url:
github_url: https://github.com/jaketarnow
gitlab_url: 
googleplus_url: 
instagram_url: https://www.instagram.com/jaketarnow/
linkedin_url: https://www.linkedin.com/in/jacob-tarnow-a792b64a/
pinterest_url:
slack_url:
twitter_url: https://twitter.com/jaketarnow

# Build settings
markdown: kramdown

sass:
  style: compressed
